service: swiftcloud
provider:
  name: aws
  runtime: nodejs18.x
  stage: swiftcloud
  region: ap-southeast-1
  memorySize: 128
functions:
  app:
    handler: app.handler
    events: 
      - http: 
          path: /
          method: ANY
          cors: true
      - http: 
          path: /{proxy+}
          method: ANY
          cors: true